# wrangler.toml (wrangler v3.78.6^)

name = "billing-app"
main = "src/index.ts"
compatibility_date = "2024-10-06"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "billing-system-db"
database_id = "5c1459c2-fd97-4775-95b9-6b6006521cf2"


[triggers]
# Schedule cron triggers:
# - At every hour
# - At 5AM on everyday
crons = [ "0 * * * *", "0 5 * * *" ]
